name: Node.js CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: self-hosted  # Use GitHub-hosted runner

    strategy:
      matrix:
        node-version: [18.x]  # Specify Node.js version(s)

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'  # Enable dependency caching

      - name: Print PATH
        run: echo $PATH

      - name: Build project
        run: npm run build --if-present

      - name: Create .env file
        run: |
          echo "${{ secrets.PROD_ENV_FILE }}" > .env
